name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      # Lint terraform pipeline with yamllint
      - name: Lint with yamllint
        run: |
          yamllint -c .yamllint.yml .github/workflows/terraform.yml

      # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.2

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: |
          terraform init \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
            -backend-config="container_name=$CONTAINER_NAME" \
            -backend-config="resource_group_name=$RESOURCE_GROUP"

      # Run a terraform plan for pull requests only
      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          fpl_password: ${{ secrets.fpl_password}}
          fpl_manager_id: ${{ vars.fpl_manager_id}}
          fpl_league_ids: ${{ vars.fpl_league_ids}}
          fpl_api_key: ${{ secrets.fpl_api_key }}
          fpl_dashboard_key: ${{ secrets.fpl_dashboard_key }}
          train_delay_username: ${{ secrets.train_delay_username}}
          train_delay_password: ${{ secrets.train_delay_password}}
        if: github.event_name == 'pull_request'
        run: |
          terraform plan \
            -var "fpl_password=$fpl_password" \
            -var "fpl_manager_id=$fpl_manager_id" \
            -var "fpl_league_ids=$fpl_league_ids" \
            -var "fpl_api_key=$fpl_api_key" \
            -var "fpl_dashboard_key=$fpl_dashboard_key" \
            -var "train_delay_username=$train_delay_username" \
            -var "train_delay_password=$train_delay_password"

        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          fpl_password: ${{ secrets.fpl_password}}
          fpl_manager_id: ${{ vars.fpl_manager_id}}
          fpl_league_ids: ${{ vars.fpl_league_ids}}
          fpl_api_key: ${{ secrets.fpl_api_key }}
          fpl_dashboard_key: ${{ secrets.fpl_dashboard_key }}
          train_delay_username: ${{ secrets.train_delay_username}}
          train_delay_password: ${{ secrets.train_delay_password}}
        run: |
          terraform apply -auto-approve \
            -var "fpl_password=$fpl_password" \
            -var "fpl_manager_id=$fpl_manager_id" \
            -var "fpl_league_ids=$fpl_league_ids" \
            -var "fpl_api_key=$fpl_api_key" \
            -var "fpl_dashboard_key=$fpl_dashboard_key" \
            -var "train_delay_username=$train_delay_username" \
            -var "train_delay_password=$train_delay_password"
